name: app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  http:
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/background.jpg
    - images/cat.jpg
    - images/ic_camera.svg
    - images/ic_key.svg
    - images/ic_witch_hat.svg

  fonts:
    - family: Harry Potter
      fonts:
        - asset: fonts/title_harry_potter.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins_Regular.ttf
        - asset: fonts/Poppins_Bold.ttf
          weight: 700